////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was not generated by a tool. but for stylecop suppression.
//// </auto-generated>
////------------------------------------------------------------------------------
namespace StrixIT.Platform.Modules.Cms.Migrations
{
    using StrixIT.Platform.Core;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<StrixIT.Platform.Modules.Cms.PlatformDataSource>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(StrixIT.Platform.Modules.Cms.PlatformDataSource context)
        {
            new MailBuilder(DependencyInjector.Get<IFileSystemWrapper>(), DependencyInjector.TryGet(typeof(IMembershipService)) as IMembershipService).InitMails(context);
        }
    }
}
