////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was not generated by a tool. but for stylecop suppression.
//// </auto-generated>
////------------------------------------------------------------------------------
namespace StrixIT.Platform.Modules.Cms.Migrations
{
    using Core.Environment;
    using StrixIT.Platform.Core;
    using System.Data.Entity.Migrations;

    internal sealed class Configuration : DbMigrationsConfiguration<PlatformDataSource>
    {
        #region Public Constructors

        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        #endregion Public Constructors

        #region Protected Methods

        protected override void Seed(PlatformDataSource context)
        {
            new MailBuilder(DependencyInjector.Get<IFileSystem>(), DependencyInjector.Get<IEnvironment>()).InitMails(context);
        }

        #endregion Protected Methods
    }
}