//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using StrixIT.Platform.Core;

namespace StrixIT.Platform.Modules.Cms.Tests
{
    public class TestPlatformDataSource : PlatformDataSource
    {
        #region Public Constructors

        public TestPlatformDataSource(IFileSystemWrapper wrapper, ICacheService cache, IUserContext user)
            : base(wrapper, cache, user)
        {
            Configuration.LazyLoadingEnabled = true;
        }

        #endregion Public Constructors
    }
}