//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using StrixIT.Platform.Core;
using System.Data.Entity;

namespace StrixIT.Platform.Modules.Cms.Tests
{
    public class TestPlatformDataSource : PlatformDataSource
    {
        public TestPlatformDataSource(IFileSystemWrapper wrapper, ICacheService cache)
            : base(wrapper, cache)
        {
            Configuration.LazyLoadingEnabled = true;
        }
    }
}
