////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was not generated by a tool. but for stylecop suppression.
//// </auto-generated>
////------------------------------------------------------------------------------

using Moq;
using StrixIT.Platform.Core;
using System;
using System.Collections.Generic;

namespace StrixIT.Platform.Modules.Cms.Tests
{
    public class EntityServiceManagerMock
    {
        #region Private Fields

        private Mock<ICmsData> _dataMock = new Mock<ICmsData>();
        private Mock<IEntityHelper> _entityHelperMock = new Mock<IEntityHelper>();
        private IEntityServiceManager _manager;
        private Mock<IPlatformHelper> _platformHelperMock = new Mock<IPlatformHelper>();

        #endregion Private Fields

        private static List<EntityType> entityTypes = new List<EntityType>
        {
            new EntityType
            {
                Id = Guid.NewGuid(),
                Name = typeof(Html).FullName
            },
            new EntityType
            {
                Id = Guid.NewGuid(),
                Name = typeof(News).FullName
            },
            new EntityType
            {
                Id = Guid.NewGuid(),
                Name = typeof(MailContentTemplate).FullName
            },
            new EntityType
            {
                Id = Guid.NewGuid(),
                Name = typeof(MailContent).FullName
            },
            new EntityType
            {
                Id = Guid.NewGuid(),
                Name = typeof(Document).FullName
            },
        };

        #region Public Constructors

        public EntityServiceManagerMock()
        {
            _platformHelperMock.Setup(p => p.Services).Returns(new PlatformHelper(null).Services);
            _entityHelperMock.Setup(h => h.EntityTypes).Returns(entityTypes);
            _dataMock.Setup(c => c.EntityHelper).Returns(_entityHelperMock.Object);
            _dataMock.Setup(c => c.PlatformHelper).Returns(_platformHelperMock.Object);
            _manager = new EntityServiceManager(_dataMock.Object);
        }

        #endregion Public Constructors

        #region Public Properties

        public Mock<ICmsData> CmsDataMock
        {
            get
            {
                return _dataMock;
            }
        }

        public IEntityServiceManager EntityServiceManager
        {
            get
            {
                return _manager;
            }
        }

        #endregion Public Properties
    }
}