////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was not generated by a tool. but for stylecop suppression.
//// </auto-generated>
////------------------------------------------------------------------------------
using Moq;
using StrixIT.Platform.Modules.Cms;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace StrixIT.Platform.Modules.Cms.Tests
{
    public class EntityServiceManagerMock
    {
        private IEntityServiceManager _manager;
        private DataSourceMock _dataSourceMock = new DataSourceMock();

        public EntityServiceManagerMock()
        {
            _manager = new EntityServiceManager(_dataSourceMock.Mock.Object);
        }

        public IEntityServiceManager EntityServiceManager
        {
            get
            {
                return _manager;
            }
        }

        public DataSourceMock DataSourceMock
        {
            get
            {
                return _dataSourceMock;
            }
        }
    }
}
