////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was not generated by a tool. but for stylecop suppression.
//// </auto-generated>
////------------------------------------------------------------------------------
using Moq;
using StrixIT.Platform.Core;
using System;

namespace StrixIT.Platform.Modules.Cms.Tests
{
    public class EntityServiceMock<TModel> where TModel : EntityViewModel
    {
        #region Private Fields

        private Mock<ICacheService> _cacheMock = new Mock<ICacheService>();
        private DataSourceMock _dataSourceMock = new DataSourceMock();
        private EntityManagerMock _entityManagerMock = new EntityManagerMock();
        private IEntityService<TModel> _service;
        private TaxonomyManagerMock _taxonomyManagerMock = new TaxonomyManagerMock();

        #endregion Private Fields

        #region Public Constructors

        public EntityServiceMock()
        {
            _service = Activator.CreateInstance(typeof(EntityService<>).MakeGenericType(typeof(TModel)), _dataSourceMock.Mock.Object, _entityManagerMock.EntityManager, _taxonomyManagerMock.TaxonomyManager, _cacheMock.Object) as IEntityService<TModel>;
        }

        #endregion Public Constructors

        #region Public Properties

        public Mock<ICacheService> CacheMock
        {
            get
            {
                return _cacheMock;
            }
        }

        public DataSourceMock DataSourceMock
        {
            get
            {
                return _dataSourceMock;
            }
        }

        public EntityManagerMock EntityManagerMock
        {
            get
            {
                return _entityManagerMock;
            }
        }

        public IEntityService<TModel> EntityService
        {
            get
            {
                return _service;
            }
        }

        public TaxonomyManagerMock TaxonomyManagerMock
        {
            get
            {
                return _taxonomyManagerMock;
            }
        }

        #endregion Public Properties
    }
}