////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was not generated by a tool. but for stylecop suppression.
//// </auto-generated>
////------------------------------------------------------------------------------

namespace StrixIT.Platform.Modules.Cms.Tests
{
    public class EntityServiceManagerMock
    {
        #region Private Fields

        private DataSourceMock _dataSourceMock = new DataSourceMock();
        private IEntityServiceManager _manager;

        #endregion Private Fields

        #region Public Constructors

        public EntityServiceManagerMock()
        {
            _manager = new EntityServiceManager(_dataSourceMock.Mock.Object);
        }

        #endregion Public Constructors

        #region Public Properties

        public DataSourceMock DataSourceMock
        {
            get
            {
                return _dataSourceMock;
            }
        }

        public IEntityServiceManager EntityServiceManager
        {
            get
            {
                return _manager;
            }
        }

        #endregion Public Properties
    }
}