//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Moq;
using StrixIT.Platform.Modules.Cms;
using StrixIT.Platform.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;

namespace StrixIT.Platform.Modules.Cms.Tests
{
    public class FileManagerMock
    {
        private IFileManager _manager;
        private DataSourceMock _dataSourceMock = new DataSourceMock();
        private Mock<IImageConverter> _imageConverterMock = new Mock<IImageConverter>();

        public FileManagerMock()
        {
            _dataSourceMock.RegisterData<EntityType>(EntityServicesTestData.EntityTypes);
            _manager = new FileManager(_dataSourceMock.Mock.Object, _imageConverterMock.Object);
        }

        public IFileManager FileManager
        {
            get
            {
                return _manager;
            }
        }

        public DataSourceMock DataSourceMock
        {
            get
            {
                return _dataSourceMock;
            }
        }
    }
}