//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Moq;

namespace StrixIT.Platform.Modules.Cms.Tests
{
    public class FileManagerMock
    {
        #region Private Fields

        private DataSourceMock _dataSourceMock = new DataSourceMock();
        private Mock<IImageConverter> _imageConverterMock = new Mock<IImageConverter>();
        private IFileManager _manager;

        #endregion Private Fields

        #region Public Constructors

        public FileManagerMock()
        {
            _dataSourceMock.RegisterData<EntityType>(EntityServicesTestData.EntityTypes);
            _manager = new FileManager(_dataSourceMock.Mock.Object, _imageConverterMock.Object);
        }

        #endregion Public Constructors

        #region Public Properties

        public DataSourceMock DataSourceMock
        {
            get
            {
                return _dataSourceMock;
            }
        }

        public IFileManager FileManager
        {
            get
            {
                return _manager;
            }
        }

        #endregion Public Properties
    }
}