//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------

using Moq;
using StrixIT.Platform.Core;
using StrixIT.Platform.Core.Environment;

namespace StrixIT.Platform.Modules.Cms.Tests
{
    public class TaxonomyManagerMock
    {
        #region Private Fields

        private Mock<ICultureService> _cultureServiceMock = new Mock<ICultureService>();
        private DataSourceMock _dataSourceMock = new DataSourceMock();
        private Mock<IEnvironment> _environmentMock = new Mock<IEnvironment>();
        private ITaxonomyManager _manager;
        private Mock<IUserContext> _userMock = new Mock<IUserContext>();

        #endregion Private Fields

        #region Public Constructors

        public TaxonomyManagerMock()
        {
            _cultureServiceMock.Setup(c => c.DefaultCultureCode).Returns("en");
            _cultureServiceMock.Setup(c => c.CurrentCultureCode).Returns("en");
            _environmentMock.Setup(e => e.Cultures).Returns(_cultureServiceMock.Object);
            _environmentMock.Setup(e => e.User).Returns(_userMock.Object);
            _manager = new TaxonomyManager(_dataSourceMock.Mock.Object, _environmentMock.Object);
        }

        #endregion Public Constructors

        #region Public Properties

        public DataSourceMock DataSourceMock
        {
            get
            {
                return _dataSourceMock;
            }
        }

        public Mock<IEnvironment> EnvironmentMock
        {
            get
            {
                return _environmentMock;
            }
        }

        public ITaxonomyManager TaxonomyManager
        {
            get
            {
                return _manager;
            }
        }

        #endregion Public Properties
    }
}