//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------

using Moq;
using StrixIT.Platform.Core;

namespace StrixIT.Platform.Modules.Cms.Tests
{
    public class TaxonomyManagerMock
    {
        #region Private Fields

        private DataSourceMock _dataSourceMock = new DataSourceMock();
        private ITaxonomyManager _manager;
        private Mock<IUserContext> _userMock = new Mock<IUserContext>();

        #endregion Private Fields

        #region Public Constructors

        public TaxonomyManagerMock()
        {
            _manager = new TaxonomyManager(_dataSourceMock.Mock.Object, _userMock.Object);
        }

        #endregion Public Constructors

        #region Public Properties

        public DataSourceMock DataSourceMock
        {
            get
            {
                return _dataSourceMock;
            }
        }

        public ITaxonomyManager TaxonomyManager
        {
            get
            {
                return _manager;
            }
        }

        public Mock<IUserContext> UserMock
        {
            get
            {
                return _userMock;
            }
        }

        #endregion Public Properties
    }
}