//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrixIT.Platform.Modules.Cms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Interface {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Interface() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StrixIT.Platform.Modules.Cms.Resources.Interface", typeof(Interface).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate draft.
        /// </summary>
        public static string ActivateDraft {
            get {
                return ResourceManager.GetString("ActivateDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tag.
        /// </summary>
        public static string AddTag {
            get {
                return ResourceManager.GetString("AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to version list.
        /// </summary>
        public static string BackToVersionList {
            get {
                return ResourceManager.GetString("BackToVersionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to view the document.
        /// </summary>
        public static string ClickToViewDocument {
            get {
                return ResourceManager.GetString("ClickToViewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really activate this draft?.
        /// </summary>
        public static string ConfirmActivateDraft {
            get {
                return ResourceManager.GetString("ConfirmActivateDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this comment?.
        /// </summary>
        public static string ConfirmDeleteComment {
            get {
                return ResourceManager.GetString("ConfirmDeleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this file?.
        /// </summary>
        public static string ConfirmDeleteFile {
            get {
                return ResourceManager.GetString("ConfirmDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restore version {0} of {1} {2}?.
        /// </summary>
        public static string ConfirmRestoreVersion {
            get {
                return ResourceManager.GetString("ConfirmRestoreVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string ContentView {
            get {
                return ResourceManager.GetString("ContentView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create document.
        /// </summary>
        public static string CreateDocument {
            get {
                return ResourceManager.GetString("CreateDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New news item.
        /// </summary>
        public static string CreateNews {
            get {
                return ResourceManager.GetString("CreateNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete comment.
        /// </summary>
        public static string DeleteComment {
            get {
                return ResourceManager.GetString("DeleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        public static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string DocumentIndex {
            get {
                return ResourceManager.GetString("DocumentIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string DownloadCount {
            get {
                return ResourceManager.GetString("DownloadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft number {0}.
        /// </summary>
        public static string DraftNumber {
            get {
                return ResourceManager.GetString("DraftNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit document.
        /// </summary>
        public static string EditDocument {
            get {
                return ResourceManager.GetString("EditDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit news item.
        /// </summary>
        public static string EditNews {
            get {
                return ResourceManager.GetString("EditNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit response.
        /// </summary>
        public static string EditResponse {
            get {
                return ResourceManager.GetString("EditResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Vocabulary.
        /// </summary>
        public static string EditVocabulary {
            get {
                return ResourceManager.GetString("EditVocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a comment.
        /// </summary>
        public static string EnterAComment {
            get {
                return ResourceManager.GetString("EnterAComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Service Actions.
        /// </summary>
        public static string EntityServiceActionIndex {
            get {
                return ResourceManager.GetString("EntityServiceActionIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving service settings.
        /// </summary>
        public static string ErrorSavingServiceAction {
            get {
                return ResourceManager.GetString("ErrorSavingServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while uploading the file.
        /// </summary>
        public static string ErrorUploadingFile {
            get {
                return ResourceManager.GetString("ErrorUploadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires at.
        /// </summary>
        public static string ExpireTime {
            get {
                return ResourceManager.GetString("ExpireTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzip files.
        /// </summary>
        public static string ExtractZip {
            get {
                return ResourceManager.GetString("ExtractZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileData {
            get {
                return ResourceManager.GetString("FileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File deleted successfully.
        /// </summary>
        public static string FileDeleteSuccess {
            get {
                return ResourceManager.GetString("FileDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file type is not allowed.
        /// </summary>
        public static string FileTypeNotAllowed {
            get {
                return ResourceManager.GetString("FileTypeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can upload these file types: {0}..
        /// </summary>
        public static string FileTypesAllowed {
            get {
                return ResourceManager.GetString("FileTypesAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded on.
        /// </summary>
        public static string FileUploadedOn {
            get {
                return ResourceManager.GetString("FileUploadedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully.
        /// </summary>
        public static string FileUploadSuccess {
            get {
                return ResourceManager.GetString("FileUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter tags....
        /// </summary>
        public static string FilterTags {
            get {
                return ResourceManager.GetString("FilterTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html.
        /// </summary>
        public static string HTML {
            get {
                return ResourceManager.GetString("HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html list.
        /// </summary>
        public static string HtmlIndex {
            get {
                return ResourceManager.GetString("HtmlIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid e-mail address.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last response date.
        /// </summary>
        public static string LastResponseDate {
            get {
                return ResourceManager.GetString("LastResponseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail index.
        /// </summary>
        public static string MailContentIndex {
            get {
                return ResourceManager.GetString("MailContentIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail template index.
        /// </summary>
        public static string MailContentTemplateIndex {
            get {
                return ResourceManager.GetString("MailContentTemplateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files can be no more than {0} MB in size..
        /// </summary>
        public static string MaxFileSize {
            get {
                return ResourceManager.GetString("MaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified by.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified on.
        /// </summary>
        public static string ModifiedOn {
            get {
                return ResourceManager.GetString("ModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name already exists..
        /// </summary>
        public static string NameNotUnique {
            get {
                return ResourceManager.GetString("NameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New response.
        /// </summary>
        public static string NewResponse {
            get {
                return ResourceManager.GetString("NewResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News list.
        /// </summary>
        public static string NewsIndex {
            get {
                return ResourceManager.GetString("NewsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News item {0}.
        /// </summary>
        public static string NewsItem {
            get {
                return ResourceManager.GetString("NewsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected.
        /// </summary>
        public static string NoFileSelected {
            get {
                return ResourceManager.GetString("NoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service settings to save.
        /// </summary>
        public static string NoRecordsToSave {
            get {
                return ResourceManager.GetString("NoRecordsToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags found.
        /// </summary>
        public static string NoTagsAvailable {
            get {
                return ResourceManager.GetString("NoTagsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of responses.
        /// </summary>
        public static string NumberOfResponses {
            get {
                return ResourceManager.GetString("NumberOfResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string OriginalFileName {
            get {
                return ResourceManager.GetString("OriginalFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file.
        /// </summary>
        public static string PleaseSelectAFile {
            get {
                return ResourceManager.GetString("PleaseSelectAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing files, please wait....
        /// </summary>
        public static string ProcessingUpload {
            get {
                return ResourceManager.GetString("ProcessingUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published by.
        /// </summary>
        public static string PublishedBy {
            get {
                return ResourceManager.GetString("PublishedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published at.
        /// </summary>
        public static string PublishedOn {
            get {
                return ResourceManager.GetString("PublishedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read full article.
        /// </summary>
        public static string ReadFullNews {
            get {
                return ResourceManager.GetString("ReadFullNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove tag.
        /// </summary>
        public static string RemoveTag {
            get {
                return ResourceManager.GetString("RemoveTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respond.
        /// </summary>
        public static string Respond {
            get {
                return ResourceManager.GetString("Respond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respond to comment.
        /// </summary>
        public static string RespondToResponse {
            get {
                return ResourceManager.GetString("RespondToResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string ResponseCreatedOn {
            get {
                return ResourceManager.GetString("ResponseCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string ResponseToVersion {
            get {
                return ResourceManager.GetString("ResponseToVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string RestoreVersion {
            get {
                return ResourceManager.GetString("RestoreVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore version {0}.
        /// </summary>
        public static string RestoreVersionTitle {
            get {
                return ResourceManager.GetString("RestoreVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchPlaceHolder {
            get {
                return ResourceManager.GetString("SearchPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results for {0}.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a zip archive.
        /// </summary>
        public static string SelectArchive {
            get {
                return ResourceManager.GetString("SelectArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File selected: {0}.
        /// </summary>
        public static string SelectedFile {
            get {
                return ResourceManager.GetString("SelectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file.
        /// </summary>
        public static string SelectSingleFile {
            get {
                return ResourceManager.GetString("SelectSingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have  {1} characters at maximum..
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomy.
        /// </summary>
        public static string TaxonomyIndex {
            get {
                return ResourceManager.GetString("TaxonomyIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated by {0} on {1}.
        /// </summary>
        public static string UpdatedByOn {
            get {
                return ResourceManager.GetString("UpdatedByOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a new file.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload multiple files.
        /// </summary>
        public static string UploadFiles {
            get {
                return ResourceManager.GetString("UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload multiple documents.
        /// </summary>
        public static string UploadMultipleDocuments {
            get {
                return ResourceManager.GetString("UploadMultipleDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version log.
        /// </summary>
        public static string VersionLog {
            get {
                return ResourceManager.GetString("VersionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version {0}.
        /// </summary>
        public static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Number.
        /// </summary>
        public static string VersionNumberHeader {
            get {
                return ResourceManager.GetString("VersionNumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View draft.
        /// </summary>
        public static string ViewDraft {
            get {
                return ResourceManager.GetString("ViewDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ViewVersion {
            get {
                return ResourceManager.GetString("ViewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocabulary.
        /// </summary>
        public static string Vocabulary {
            get {
                return ResourceManager.GetString("Vocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string VocabularyTags {
            get {
                return ResourceManager.GetString("VocabularyTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple files must be zipped into one file before uploading.
        /// </summary>
        public static string ZippedFileInstructions {
            get {
                return ResourceManager.GetString("ZippedFileInstructions", resourceCulture);
            }
        }
    }
}
