////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was not generated by a tool. but for stylecop suppression.
//// </auto-generated>
////------------------------------------------------------------------------------
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using System;
using System.Collections.Generic;
using System.Linq;

namespace StrixIT.Platform.Modules.Cms.Tests
{
    [TestClass]
    public class EntityServiceManagerTests
    {
        #region Private Fields

        private static List<EntityType> entityTypes = new List<EntityType>
        {
            new EntityType
            {
                Id = Guid.NewGuid(),
                Name = typeof(Html).FullName
            },
            new EntityType
            {
                Id = Guid.NewGuid(),
                Name = typeof(News).FullName
            },
            new EntityType
            {
                Id = Guid.NewGuid(),
                Name = typeof(MailContentTemplate).FullName
            },
            new EntityType
            {
                Id = Guid.NewGuid(),
                Name = typeof(MailContent).FullName
            },
            new EntityType
            {
                Id = Guid.NewGuid(),
                Name = typeof(Document).FullName
            },
        };

        private List<Mock> _mocks;

        #endregion Private Fields

        #region Public Methods

        [TestMethod()]
        public void GetManagerActionRecordsShouldReturnCorrectNumberOfRecords()
        {
            var mock = new EntityServiceManagerMock();
            var platformHelperMock = _mocks.First(m => m.GetType().Equals(typeof(Mock<IPlatformHelper>))) as Mock<IPlatformHelper>;
            var entityHelperMock = _mocks.First(m => m.GetType().Equals(typeof(Mock<IEntityHelper>))) as Mock<IEntityHelper>;
            StrixCms.SetHelper(new DefaultPlatformHelper(null));
            var entityHelper = new DefaultEntityHelper(entityTypes);
            EntityHelper.SetHelper(entityHelper);
            var result = mock.EntityServiceManager.GetManagerActionRecords();
            StrixCms.SetHelper(platformHelperMock.Object);
            EntityHelper.SetHelper(entityHelperMock.Object);
            Assert.IsNotNull(result);
            Assert.AreEqual(5, result.Count);
            Assert.AreEqual(10, result.First().Item3.Count);
        }

        [TestInitialize]
        public void Init()
        {
            _mocks = TestHelpers.MockUtilities();
        }

        #endregion Public Methods
    }
}