////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was not generated by a tool. but for stylecop suppression.
//// </auto-generated>
////------------------------------------------------------------------------------
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using StrixIT.Platform.Core;
using System;
using System.Collections.Generic;
using System.Linq;

namespace StrixIT.Platform.Modules.Cms.Tests
{
    [TestClass]
    public class EntityServiceManagerTests
    {
        #region Public Methods

        [TestMethod()]
        public void GetManagerActionRecordsShouldReturnCorrectNumberOfRecords()
        {
            var mock = new EntityServiceManagerMock();
            var result = mock.EntityServiceManager.GetManagerActionRecords();
            Assert.IsNotNull(result);
            Assert.AreEqual(5, result.Count);
            Assert.AreEqual(10, result.First().Item3.Count);
        }

        #endregion Public Methods
    }
}