////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was not generated by a tool. but for stylecop suppression.
//// </auto-generated>
////------------------------------------------------------------------------------
using Moq;
using StrixIT.Platform.Modules.Cms;
using StrixIT.Platform.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace StrixIT.Platform.Modules.Cms.Tests
{
    public class EntityManagerMock
    {
        private IEntityManager _manager;
        private DataSourceMock _dataSourceMock = new DataSourceMock();
        private Mock<ICacheService> _cacheMock = new Mock<ICacheService>();

        public EntityManagerMock()
        {
            _dataSourceMock.RegisterData<PlatformEntity>(EntityServicesTestData.Entities);
            _dataSourceMock.RegisterData<News>(EntityServicesTestData.Content);
            _manager = new EntityManager(_dataSourceMock.Mock.Object, _cacheMock.Object);
        }

        public IEntityManager EntityManager
        {
            get
            {
                return _manager;
            }
        }

        public DataSourceMock DataSourceMock
        {
            get
            {
                return _dataSourceMock;
            }
        }

        public Mock<ICacheService> CacheMock
        {
            get
            {
                return _cacheMock;
            }
        }
    }
}
