////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was not generated by a tool. but for stylecop suppression.
//// </auto-generated>
////------------------------------------------------------------------------------
using Moq;
using StrixIT.Platform.Core;
using System;
using System.Collections.Generic;

namespace StrixIT.Platform.Modules.Cms.Tests
{
    public static class TestHelpers
    {
        #region Public Fields

        public static string CurrentCulture = "en";
        public static Guid CurrentUserCurrentGroupId = Guid.NewGuid();
        public static Guid CurrentUserId = Guid.NewGuid();
        public static string DutchCulture = "nl";

        #endregion Public Fields

        #region Public Methods

        public static List<Mock> MockUtilities()
        {
            var mocks = new List<Mock>();
            var userContext = new Mock<IUserContext>();
            userContext.Setup(m => m.Id).Returns(CurrentUserId);
            userContext.Setup(m => m.GroupId).Returns(CurrentUserCurrentGroupId);
            mocks.Add(userContext);
            StrixPlatform.User = userContext.Object;

            var environment = new DefaultEnvironment();
            StrixPlatform.Environment = environment;

            var dependencyInjectorMock = new Mock<IDependencyInjector>();
            DependencyInjector.Injector = dependencyInjectorMock.Object;
            dependencyInjectorMock.Setup(d => d.TryGet<IMembershipService>()).Returns((IMembershipService)null);
            mocks.Add(dependencyInjectorMock);

            var entityHelper = new Mock<IEntityHelper>();
            EntityHelper.SetHelper(entityHelper.Object);
            mocks.Add(entityHelper);

            var platformHelperMock = new Mock<IPlatformHelper>();
            mocks.Add(platformHelperMock);
            StrixCms.SetHelper(platformHelperMock.Object);

            return mocks;
        }

        #endregion Public Methods
    }
}