#region Apache License
//-----------------------------------------------------------------------
// <copyright file="EntityServiceActions.cs" company="StrixIT">
// Copyright 2015 StrixIT. Author R.G. Schurgers MA MSc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//-----------------------------------------------------------------------
#endregion

namespace StrixIT.Platform.Modules.Cms
{
    /// <summary>
    /// An enumeration for all platform-supported entity service actions.
    /// </summary>
    public static class EntityServiceActions
    {
        /// <summary>
        /// The Access service action to allow specifying access to entity types.
        /// </summary>
        public static readonly string EntityTypeAccess = "EntityTypeAccess";

        /// <summary>
        /// The Access service action to allow specifying access to individual content items.
        /// </summary>
        public static readonly string ItemAccess = "ItemAccess";

        /// <summary>
        /// The AllowComments service action.
        /// </summary>
        public static readonly string AllowComments = "AllowComments";

        /// <summary>
        /// The AllowNestedComments service action.
        /// </summary>
        public static readonly string AllowNestedComments = "AllowNestedComments";

        /// <summary>
        /// The ModerateComments service action.
        /// </summary>
        public static readonly string ModerateComments = "ModerateComments";

        /// <summary>
        /// The RTE advanced service action. When enabled, the RTE editor will show the advanced options.
        /// </summary>
        public static readonly string RteAdvanced = "Advanced";

        /// <summary>
        /// The RTE File Upload service action. When enabled, users can upload files in the RTE editor.
        /// </summary>
        public static readonly string RteFileUpload = "FileUpload";

        /// <summary>
        /// The RTE Html edit service action. When enabled, users can edit the HTML generated by the RTE editor.
        /// </summary>
        public static readonly string HtmlEditor = "HtmlEditor";

        /// <summary>
        /// The UpdatePaths service action.
        /// </summary>
        public static readonly string UpdatePaths = "UpdatePaths";

        /// <summary>
        /// The AllowFixedTagging service action.
        /// </summary>
        public static readonly string AllowFixedTagging = "AllowFixedTagging";

        /// <summary>
        /// The AllowFreeTagging service action.
        /// </summary>
        public static readonly string AllowFreeTagging = "AllowFreeTagging";

        /// <summary>
        /// The Translations service action.
        /// </summary>
        public static readonly string Translations = "Translations";

        /// <summary>
        /// The automatic versions service action.
        /// </summary>
        public static readonly string AutomaticVersions = "AutomaticVersions";

        /// <summary>
        /// The Drafts service action.
        /// </summary>
        public static readonly string Drafts = "Drafts";

        /// <summary>
        /// The Trashbin service action.
        /// </summary>
        public static readonly string Trashbin = "Trashbin";

        /// <summary>
        /// The Allow non-unique names service action.
        /// </summary>
        public static readonly string AllowNonUniqueNames = "AllowNonUniqueNames";

        /// <summary>
        /// The Allow anonymous access service action. When enabled, anonymous users are able to retrieve entities and lists of entities of
        /// the type the action is active for.
        /// </summary>
        public static readonly string AllowAnonymousAccess = "AllowAnonymousAccess";
    }
}